### ISSUE TITLE
www-data doesnt have permission to control pm2 instance?

### ISSUE THREAD

**Issue by lfsaga** [jalallinux/php-pm2#10]
Hi!
I'll appreciate any help regarding executing some commands from this package from a www-data instance, that is because when I use my system user with proper permissions, all the process and pm2 works well but when this is triggered from Laravel context like a Controller is not updating the pm2 processes instances and seems to be permission-related.
I'm running in apache2.

**Comment by jalallinux** [comment]
Hi
You can use prefix to run command like this:
```php
pm2('runuser -u www-data')->list()
pm2('runuser -u www-data')->start()
```
